default_config:
logger:
  default: info

lovelace:
  mode: yaml
  resources:
    - url: http://127.0.0.1:5000/ha-selector-keypad.js
      type: module
  dashboards:
    test-dashboard:
      mode: yaml
      filename: test-dashboard.yaml
      title: Testing
      icon: mdi:tools
      show_in_sidebar: true