name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Build the plugin"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}"
          npm install
          npm run build
